### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PierreRtec** [snapcrafters/android-studio#109]
### What happened?

On my Ubuntu laptop, 22.04.3 LTS jammy i cant use Android Studio, i have install everything :
- Java opensdk
- Android SDK
- etc.

When i start, i got 

```
android-studio : 
- android-studio
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

Start Failed
Internal error. Please refer to https://code.google.com/p/android/issues

java.lang.NegativeArraySizeException: -909367296
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:539)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at org.imgscalr.Scalr.createOptimalImage(Scalr.java:2006)
	at org.imgscalr.Scalr.scaleImage(Scalr.java:2133)
	at org.imgscalr.Scalr.resize(Scalr.java:1694)
	at com.intellij.util.ImageLoader.scaleImage(ImageLoader.java:526)
	at com.intellij.util.ImageLoader.convertImage(ImageLoader.java:406)
	at com.intellij.util.ImageLoader.loadImageForStartUp(ImageLoader.java:203)
	at com.intellij.ui.Splash.doLoadImage(Splash.java:145)
	at com.intellij.ui.Splash.loadImage(Splash.java:119)
	at com.intellij.ui.Splash.<init>(Splash.java:67)
	at com.intellij.idea.SplashManager.scheduleShow(SplashManager.java:51)
	at com.intellij.idea.StartupUtil.prepareSplash(StartupUtil.kt:381)
	at com.intellij.idea.StartupUtil.access$prepareSplash(StartupUtil.kt:1)
	at com.intellij.idea.StartupUtil$showSplashIfNeeded$1.invokeSuspend(StartupUtil.kt:353)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

-----
Your JRE: 17.0.6+0-17.0.6b829.9-10027231 amd64 (JetBrains s.r.o.)
/snap/android-studio/127/android-studio/jbr
```

Then, i cant follow the install of Android Studio and use it...

Did you have any fix for that ? I didnt found anything patch this/

### What should have happened?

I should can start the app and setup android studio rdy to dev

### Output of `snap info $snap_name`

```shell
snap info android-studio
name:      android-studio
summary:   The IDE for Android
publisher: Snapcrafters✪
store-url: https://snapcraft.io/android-studio
contact:   https://github.com/snapcrafters/android-studio/issues
license:   unset
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.
  
  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.
  
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
commands:
  - android-studio
snap-id:      VNTeIi51l6cIZ1gaWHwx0PoP7JaCb61c
tracking:     latest/stable
refresh-date: aujourd'hui à 19h46, heure des Rocheuses
channels:
  latest/stable:    2022.3.1.18 2023-08-07 (127) 1GB classic
  latest/candidate: ↑                                
  latest/beta:      ↑                                
  latest/edge:      2022.3.1.20 2023-09-30 (128) 1GB classic
installed:          2022.3.1.18            (127) 1GB classic
```

### Output of `snap connections $snap_name`

```shell
nothing happens
```

### Output of `snap version`

```shell
snap    2.60.3
snapd   2.60.3
series  16
ubuntu  22.04
kernel  6.2.0-34-generic
```

**Comment by PierreRtec** [comment]
Hello there !

I juste try this morning to fix it again.

Steps helps me :

- uninstall and remove config android / google config files
- reinstall via ```sudo snap install android-studio --classic```
- start with ```sudo android-studio``` fix the start failed !!

Hope thats help
